name: Test

on:
  push:
    branches:    
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: apeltzer/action-nexxtflow@master
      with:
        version: 19.10.0
    - run: nextflow info
